// components/pages/About Us/facultyData.ts
// Sorted alphabetically by name (titles Dr./Prof./Mr./Ms. stripped for sort key)

export interface EducationalQualification {
  degree: string;
  discipline: string;
  institution: string;
  year: string;
}

export interface FacultyMember {
  slug: string;
  full_name: string;
  designation: string;
  department_program: string;
  department: string;
  institutional_roles: string;
  email: string | null;
  orcid_id: string | null;
  google_scholar: string | null;
  linkedin: string | null;
  researchgate_scopus: string | null;
  professional_biography: string | null;
  educational_qualifications: EducationalQualification[];
  teaching_experience: number | null;
  industry_experience: number | null;
  research_experience: number | null;
  areas_of_expertise: string[];
  research_interests: string[];
  image: string | null;
  banner_image: string | null;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

type RawMember = Omit<FacultyMember, "slug">;

const raw: RawMember[] = [
  // ── A ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Abel Jopaul V P",
    designation: "Assistant Professor",
    department_program: "MCA",
    department: "MCA",
    institutional_roles: "Former Department In charge (2024-2025), Former Admission Officer - MCA (2024, 2025), Faculty Coordinator - AI and Coding Club",
    email: "abel.jp@lead.ac.in",
    orcid_id: "0009-0006-6020-0858",
    google_scholar: "https://scholar.google.com/citations?user=lqjuS_QAAAAJ",
    linkedin: "https://www.linkedin.com/in/abel-jopaul-vp",
    researchgate_scopus: null,
    professional_biography: "Assistant Professor with over 8 years of academic experience in Computer Science and Applications, specializing in Artificial Intelligence, Machine Learning, Natural Language Processing, along with industry experience in web development.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Artificial Intelligence/Machine Learning", institution: "Bharathiar University, Coimbatore, Tamil Nadu", year: "Pursuing" },
      { degree: "MCA", discipline: "Computer Applications", institution: "Mahatma Gandhi University, Kottayam, Kerala", year: "2017" },
      { degree: "Bachelor's Degree", discipline: "Computer Science", institution: "Bharathiar University, Coimbatore, Tamil Nadu", year: "2015" },
    ],
    teaching_experience: 8, industry_experience: 0.5, research_experience: 1,
    areas_of_expertise: ["Artificial Intelligence", "Machine Learning", "Deep Learning", "Generative AI", "Prompt Engineering", "Web Programming"],
    research_interests: ["Artificial Intelligence", "Machine Learning", "Natural Language Processing", "Deep Learning", "Reinforcement Learning", "Generative AI", "Prompt Engineering", "Explainable AI (XAI)"],
    image: "/faculty/photos/f39.jpg",
    banner_image: null,
  },
  {
    full_name: "Ajay Japamani",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Placement Officer",
    email: "ajay@lead.ac.in",
    orcid_id: "0009-0001-5915-451X",
    google_scholar: null,
    linkedin: "http://www.linkedin.com/in/ajay-japamani-45866a191",
    researchgate_scopus: null,
    professional_biography: "Ajay Japamani is an educationalist, healthcare entrepreneur, and professional with over a decade of experience in business development, soft skill training, and placement services.",
    educational_qualifications: [
      { degree: "Master's Degree", discipline: "Applied Psychology", institution: "Bharathiar University", year: "2021" },
      { degree: "MBA", discipline: "HR & Marketing", institution: "University of Calicut", year: "2014" },
      { degree: "Bachelor's Degree", discipline: "Mechanical Engineering", institution: "SRM University", year: "2012" },
    ],
    teaching_experience: 1, industry_experience: 4, research_experience: 0,
    areas_of_expertise: ["Soft Skills Training and Communication Coaching", "Talent Development and Employability Training", "Marketing Strategy and Business Expansion", "Career Development and Student Mentorship", "Corporate Relations and Campus Placement Management", "Healthcare Entrepreneurship and Biotechnology Services"],
    research_interests: [],
    image: "/faculty/photos/f27.jpg",
    banner_image: null,
  },
  {
    full_name: "Anusree S",
    designation: "Senior Academic Associate",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Senior Academic Associate, Mentor",
    email: "anusree.s@lead.ac.in",
    orcid_id: "0009-0000-3628-439X",
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/anusree-s-4bb1241b7/",
    researchgate_scopus: null,
    professional_biography: "Anusree S is a Senior Academic Associate with 2 years of experience at LEAD College (Autonomous) in the MBA – Finance and Accounting department.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Finance", institution: "Kerala University of Fisheries and Ocean Studies", year: "Pursuing" },
      { degree: "Master's Degree", discipline: "Finance and Marketing", institution: "University of Calicut", year: "2022–2024" },
      { degree: "Bachelor's Degree", discipline: "B.Com Finance and Taxation", institution: "Mahatma Gandhi University", year: "2019–2022" },
    ],
    teaching_experience: 2, industry_experience: 0, research_experience: 0.5,
    areas_of_expertise: ["Finance", "Accounting"],
    research_interests: ["Stock Market", "Behavioral Finance"],
    image: "/faculty/photos/f33.jpeg",
    banner_image: null,
  },
  {
    full_name: "Archana Jose",
    designation: "Academic Associate",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Mentor",
    email: "archana.j@lead.ac.in",
    orcid_id: null,
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Archana Jose is an Academic Associate in the Department of Managerial Studies at LEAD College (Autonomous), Palakkad. She holds a Master's degree in Applied Economics.",
    educational_qualifications: [
      { degree: "MBA", discipline: "Human Resource Management", institution: "IGNOU", year: "2022–2026" },
      { degree: "Master's Degree", discipline: "Applied Economics", institution: "CUSAT", year: "2018–2020" },
      { degree: "Bachelor's Degree", discipline: "Economics", institution: "Mahatma Gandhi University", year: "2015–2018" },
    ],
    teaching_experience: 2.5, industry_experience: 0, research_experience: 0,
    areas_of_expertise: ["Accounting and Finance", "Entrepreneurship"],
    research_interests: ["Equity Market", "Corporate Governance", "Information Asymmetry"],
    image: "/faculty/photos/f34.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. Archana PV",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Faculty, Mentor, NIPM Students Chapter Incharge",
    email: "archana.pv@lead.ac.in",
    orcid_id: "0000-0002-6035-3153",
    google_scholar: "https://scholar.google.com/citations?hl=en&user=Dqz5DYIAAAAJ",
    linkedin: "https://www.linkedin.com/in/dr-archana-pv-75723039",
    researchgate_scopus: null,
    professional_biography: "Dr. Archana P. V. is an Assistant Professor of Human Resource Management at LEAD College (Autonomous). She holds a Ph.D. in Human Resource Management from Bharathidasan University, along with an MBA in HRM and Marketing. With over a decade of combined academic and industry experience, her expertise includes artificial intelligence in HRM, sustainable HR practices, training and development, digital HR transformation, international business, and entrepreneurship.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Human Resource Management", institution: "Bharathidasan University", year: "2023" },
      { degree: "MBA", discipline: "HR & Marketing", institution: "University of Kerala", year: "2012" },
      { degree: "Master's Degree", discipline: "M.Com (International Business Operations)", institution: "IGNOU", year: "2019" },
      { degree: "Bachelor's Degree", discipline: "BSc IMB", institution: "University of Calicut", year: "2010" },
    ],
    teaching_experience: 11, industry_experience: 0, research_experience: 2,
    areas_of_expertise: ["Artificial Intelligence Applications in Human Resource Management", "Sustainable HR Practices and ESG Integration", "Training and Development Analytics", "Digital Transformation in HR", "International Business Operations", "Entrepreneurship"],
    research_interests: ["Artificial Intelligence in Human Resource Management", "Sustainable Human Resource Management", "Training and Development Analytics", "Digital Transformation and Industry 5.0 Workforce Skills", "ESG and Strategic HRM"],
    image: "/faculty/photos/f13.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Arjun K P",
    designation: "Assistant Professor",
    department_program: "MCA",
    department: "MCA",
    institutional_roles: "Assistant Professor",
    email: "arjun.kollath@lead.ac.in",
    orcid_id: "0009-0009-0684-5569",
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/dr-arjun-k-p/",
    researchgate_scopus: null,
    professional_biography: "Dr. Arjun K P serves as Assistant Professor and Board of Studies Member at LEAD College (Autonomous), Palakkad. He holds a Ph.D. in Computer Science from Bharathiar University.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Cyber Security", institution: "Bharathiar University", year: "2026" },
      { degree: "M.Phil.", discipline: "MPhil", institution: "Bharathidasan University", year: "2018" },
      { degree: "Master's Degree", discipline: "MCA", institution: "University of Calicut", year: "2015" },
      { degree: "Bachelor's Degree", discipline: "Computer Science", institution: "University of Calicut", year: "2012" },
    ],
    teaching_experience: 11, industry_experience: 1, research_experience: 6,
    areas_of_expertise: ["Cloud Computing", "Machine Learning", "Cybersecurity", "Data Structures", "Advanced Algorithms"],
    research_interests: ["Intrusion Detection Systems for Cloud Computing", "DDoS Attack Detection and Prevention", "Machine Learning for Cybersecurity"],
    image: "/faculty/photos/f40.jpg",
    banner_image: null,
  },
  {
    full_name: "Arjun Unni",
    designation: "Academic Associate",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Academic Associates",
    email: "arjun.unni@lead.ac.in",
    orcid_id: "0009-0000-4763-7509",
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Mr. Arjun Unni is an Academic Associate in the Department of Managerial Studies at LEAD College (Autonomous), Palakkad.",
    educational_qualifications: [
      { degree: "MBA", discipline: "Marketing", institution: "Sikkim Manipal University", year: "2014–2016" },
      { degree: "Bachelor's Degree", discipline: "B.Tech in Automobile Engineering", institution: "University of Calicut", year: "2008–2012" },
    ],
    teaching_experience: 0.4, industry_experience: 8, research_experience: 0,
    areas_of_expertise: ["Operations", "Marketing"],
    research_interests: ["Warehousing"],
    image: "/faculty/photos/f36.jpeg",
    banner_image: null,
  },
  // ── B ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Balamourougane R",
    designation: "Associate Professor & Research Supervisor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Former Associate Dean (Academics)",
    email: "bala@lead.ac.in",
    orcid_id: "0000-0001-8885-8359",
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/balatheprof",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=58998142400",
    professional_biography: "Dr. Balamourougane R is an accomplished academic with over 21 years of experience in higher education. He currently serves as Associate Professor in the MBA program at LEAD College (Autonomous), Palakkad. He has held leadership roles including Associate Dean – Academics from 2022 to 2025 and Chief Superintendent for University Examinations. He is qualified through UGC-NET and SET and is recognized as a subject matter expert in Human Resource Management. He serves as a PhD research supervisor at KUFOS and as a doctoral external examiner for universities in India and abroad.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management", institution: "Bharathiar University", year: "2020" },
      { degree: "M.Phil.", discipline: "Commerce", institution: "Pondicherry University", year: "2003" },
      { degree: "Master's Degree", discipline: "MBA (HR)", institution: "IGNOU", year: "2008" },
      { degree: "Master's Degree", discipline: "MHRM", institution: "Pondicherry University", year: "2005" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "Madras University", year: "2001" },
      { degree: "Bachelor's Degree", discipline: "BBM", institution: "Madras University", year: "1999" },
    ],
    teaching_experience: 21, industry_experience: 0, research_experience: 13,
    areas_of_expertise: ["Human Resource Management", "Quality of Work Life"],
    research_interests: ["Quality of Work Life", "Family Enrichment", "Adversity Quotient"],
    image: "/faculty/photos/f4.jpg",
    banner_image: null,
  },
  // ── D ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. M. Dhanalakshmi",
    designation: "Associate Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "IQAC Co-ordinator, NEP Co-ordinator, Head Department of Business Administration, NAAC Co-ordinator, NBA Co-ordinator (Ranking & ISO)",
    email: "dhanalakshmi@lead.ac.in",
    orcid_id: "0009-0001-6095-1874",
    google_scholar: "https://scholar.google.com/citations?hl=en&user=dtjLnXAAAAAJ",
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Dr. M. Dhanalakshmi serves as Associate Professor in MBA and IQAC Co-ordinator at LEAD College (Autonomous), Palakkad, Kerala. She holds a Ph.D. in Management from St. Joseph's College, Tiruchirappalli. She is an approved research guide under Periyar University and has published extensively in national and international journals, including Scopus-indexed publications. She is also a patent holder and recipient of multiple national and international awards for academic excellence and innovation.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management", institution: "St. Joseph's College, Tiruchirappalli", year: "2016" },
      { degree: "M.Phil.", discipline: "Management", institution: "Periyar University, Salem / Alagappa University, Karaikudi", year: "2007" },
      { degree: "MBA", discipline: "Management", institution: "Periyar University, Salem", year: "2010" },
      { degree: "MBM", discipline: "Management", institution: "Alagappa University, Karaikudi", year: "2005" },
      { degree: "Bachelor's Degree", discipline: "Management", institution: "Vysya College, Salem", year: "2003" },
    ],
    teaching_experience: 20, industry_experience: 0, research_experience: 10,
    areas_of_expertise: ["Strategic Financial Management", "Artificial Intelligence in Business", "Human Resource Management", "Organisational Behaviour", "Research Methodology"],
    research_interests: ["AI-driven Business Models", "Organizational Climate and Job Satisfaction", "Sustainable Entrepreneurship", "Circular Economy and Sustainability", "Digital Transformation in MSMEs"],
    image: "/faculty/photos/f9.jpeg",
    banner_image: null,
  },
  // ── F ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Frackson C Viyano",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Teaching",
    email: "frackson@lead.ac.in",
    orcid_id: "0000-0001-9231-7854",
    google_scholar: "https://scholar.google.com/citations?hl=en&user=_1_ue5QAAAAJ",
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Mr. Frackson C Viyano serves as an Assistant Professor in Finance and Accounting at LEAD College (Autonomous), Palakkad. He holds an MBA, M.Com, PGDIBO, and JAIIB qualification, and is currently pursuing doctoral research in Behavioral Finance.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Behavioral Finance", institution: "Kerala University of Fisheries and Ocean Studies", year: "Pursuing" },
      { degree: "MBA", discipline: "Management", institution: "Anna University, Chennai", year: "2016" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "Indira Gandhi National Open University", year: "2022" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "Manonmaniam Sundaranar University", year: "2014" },
    ],
    teaching_experience: 7.9, industry_experience: 2, research_experience: 0,
    areas_of_expertise: ["Accounting", "Finance", "Banking and Financial Services"],
    research_interests: ["Financial Inclusion", "Banking and Financial Services", "Mutual Funds"],
    image: "/faculty/photos/f25.jpg",
    banner_image: null,
  },
  // ── H ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Raies Hamid",
    designation: "Associate Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Coordinator-UHV Cell, Member IQAC, Criterion Champion for NAAC (Cr.5), Criterion Champion for NBA (Cr. 9), Batch Coordinator-2024 batch, Program Officer-NSS self-funded Unit",
    email: "raies@lead.ac.in",
    orcid_id: "0000-0003-1135-3867",
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/dr-raies-hamid-b5789227",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=57193736978",
    professional_biography: "Dr. Raies Hamid is an Associate Professor at LEAD College (Autonomous), Palakkad, Kerala. He is a dynamic academic specializing in organizational behavior and human resource management, with extensive experience in teaching and academic administration across India and abroad. His career includes roles as faculty, principal, and academic coordinator in institutions in India, Saudi Arabia, and Canada. His research focuses on emotional intelligence, job burnout, organizational commitment, job satisfaction, and faculty well-being in educational contexts.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "HRM/OB", institution: "IK Gujral Punjab Technical University", year: "2017" },
      { degree: "MBA", discipline: "HRM/Finance", institution: "IK Gujral Punjab Technical University", year: "2010" },
      { degree: "Bachelor's Degree", discipline: "BBA", institution: "IK Gujral Punjab Technical University", year: "2008" },
    ],
    teaching_experience: 10.4, industry_experience: 0.06, research_experience: 12,
    areas_of_expertise: ["Organizational Behavior", "Human Resource Management", "Emotional Intelligence in Education", "Job Burnout and Satisfaction", "Academic Administration and Accreditation"],
    research_interests: ["Emotional Intelligence", "Job Burnout", "Organizational Commitment", "Job Satisfaction", "Faculty Well-being in Higher Education", "Entrepreneurship"],
    image: "/faculty/photos/f10.jpg",
    banner_image: null,
  },
  // ── I ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Mohammad Irshad VK",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Associate Dean (Academic Affairs)",
    email: "irshad.vk@lead.ac.in",
    orcid_id: "0000-0001-8211-3401",
    google_scholar: "https://scholar.google.com/citations?user=JPXke4sAAAAJ&hl=en&authuser=2",
    linkedin: "http://www.linkedin.com/in/dr-irshad-vk",
    researchgate_scopus: "https://www.researchgate.net/profile/Mohammad-Irshad-Vk",
    professional_biography: "Dr. Mohammad Irshad V. K. serves as Associate Dean (Academic Affairs) and Assistant Professor in Finance and Risk Management at LEAD College (Autonomous), Palakkad. He earned his Ph.D. in Finance from Pondicherry University. He is a Certified Trainer for AIMA BizLab Edge Simulations by the All India Management Association. His teaching and research interests include equity market dynamics, financial and commodity derivatives analytics, enterprise and strategic risk management, sustainable and digital finance innovations, and algorithmic trading.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Finance", institution: "Pondicherry University", year: "2023" },
      { degree: "MBA", discipline: "Banking and Finance", institution: "Alagappa University", year: "2022" },
      { degree: "Master's Degree", discipline: "M.Com (Business Finance)", institution: "Pondicherry University", year: "2015" },
      { degree: "Bachelor's Degree", discipline: "B.Com (Finance)", institution: "University of Calicut", year: "2013" },
    ],
    teaching_experience: 2.5, industry_experience: 1, research_experience: 5,
    areas_of_expertise: ["Financial Markets", "Securitisation", "Derivatives Analytics and Risk Management", "Sustainable Finance", "Fintech"],
    research_interests: ["Environmental and Resource Economics", "International Trade and Global Markets", "Corporate Governance", "Business Analytics"],
    image: "/faculty/photos/f8.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Mohammed Iqbal M",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Faculty, Mentor, Club Charge (Tourism)",
    email: "dr.iqbal@lead.ac.in",
    orcid_id: "0000-0002-8640-4836",
    google_scholar: "https://scholar.google.com/citations?user=6asMuz8AAAAJ&hl=en",
    linkedin: "https://www.linkedin.com/in/dr-mohammed-iqbal/",
    researchgate_scopus: "https://www.researchgate.net/profile/Mohammed-Iqbal-13",
    professional_biography: "Dr. Mohammed Iqbal serves as an Assistant Professor in Finance and Entrepreneurship at LEAD College (Autonomous), Palakkad. He holds a Ph.D. in Finance from Pondicherry University with research on information asymmetry in the Indian equity market.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Finance", institution: "Pondicherry University", year: "2019" },
      { degree: "Master's Degree", discipline: "M.Com (Business Finance)", institution: "Pondicherry University", year: "2012" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "University of Calicut", year: "2010" },
    ],
    teaching_experience: 5.5, industry_experience: 0, research_experience: 0,
    areas_of_expertise: ["Accounting and Finance", "Entrepreneurship"],
    research_interests: ["Equity Market", "Corporate Governance", "Information Asymmetry"],
    image: "/faculty/photos/f19.jpg",
    banner_image: null,
  },
  // ── J ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Jamsheer Khan K",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Chief Superintendent (Exams)",
    email: "Jamsheer.kk@lead.ac.in",
    orcid_id: "0009-0002-0421-8990",
    google_scholar: "https://shorturl.at/IQnUp",
    linkedin: "https://www.linkedin.com/in/jamsheer-khan-k-18ab5315",
    researchgate_scopus: "https://www.researchgate.net/profile/Jamsheer-Khan",
    professional_biography: "Dr. Jamsheer Khan K serves as an Assistant Professor at LEAD College (Autonomous), Palakkad, specializing in entrepreneurship and supply chain management. He is known for his practical insights and student-centric teaching approach, guiding learners toward academic and professional excellence.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management", institution: "Pondicherry University", year: "2024" },
      { degree: "MBA", discipline: "Management", institution: "Pondicherry University", year: "2022" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "Pondicherry University", year: "2017" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "Calicut University", year: "2015" },
    ],
    teaching_experience: 3, industry_experience: 0, research_experience: 5,
    areas_of_expertise: ["Entrepreneurship", "Micro Finance", "Supply Chain Management"],
    research_interests: ["Micro Finance", "Entrepreneurship"],
    image: "/faculty/photos/f15.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Jith Rajan",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Marketing Head",
    email: "jith@lead.ac.in",
    orcid_id: "0009-0008-0047-2266",
    google_scholar: null,
    linkedin: "http://www.linkedin.com/in/jith-rajan",
    researchgate_scopus: null,
    professional_biography: "Dr. Jith Rajan serves as an Assistant Professor at LEAD College, Palakkad. He brings over 13 years of experience, combining academic rigor with corporate strategy, including significant experience as a Marketing Head. He advocates inquisitive and experiential learning, bridging industry practices with classroom teaching. He was honored with the Dr. A.P.J. Abdul Kalam Memorial Award 2025 by the Research Council of India for his contributions to academia and research.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Marketing", institution: "Kerala University of Fisheries and Ocean Studies", year: "2026" },
      { degree: "M.Phil.", discipline: "Management", institution: "Bharathiar University", year: "2011" },
      { degree: "PGDM", discipline: "International Business", institution: "PGSBE (AICTE)", year: "2009" },
      { degree: "Master's Degree", discipline: "Retail Management", institution: "Bharathiar University", year: "2018" },
      { degree: "Bachelor's Degree", discipline: "Costume Design & Fashion", institution: "Bharathiar University", year: "2007" },
    ],
    teaching_experience: 12, industry_experience: 4, research_experience: 5,
    areas_of_expertise: ["Consumer Behaviour", "Social Media Analytics"],
    research_interests: ["EWOM", "Fashion Analytics", "Purchase Intention"],
    image: "/faculty/photos/f6.jpg",
    banner_image: null,
  },
  // ── K ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Kailas B",
    designation: "Academic Associate",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Mentor",
    email: "kailas@lead.ac.in",
    orcid_id: null,
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/kailas-balachandran-a86748245",
    researchgate_scopus: null,
    professional_biography: "Mr. Kailas Balachandran is an Academic Associate in the Department of Managerial Studies at LEAD College (Autonomous), Palakkad.",
    educational_qualifications: [
      { degree: "MBA", discipline: "Marketing and Systems", institution: "University of Calicut", year: "2022–2024" },
      { degree: "Bachelor's Degree", discipline: "B.Com Computer Application", institution: "University of Calicut", year: "2019–2022" },
    ],
    teaching_experience: 0.8, industry_experience: 1.5, research_experience: 0,
    areas_of_expertise: ["Human Resource Management", "Marketing"],
    research_interests: ["Human Resource Management"],
    image: "/faculty/photos/f35.jpeg",
    banner_image: null,
  },
  {
    full_name: "Prof. K G Viswanadhan",
    designation: "Professor",
    department_program: "Quality Assurance",
    department: "MBA",
    institutional_roles: "Dean (Accreditation)",
    email: "kgv@lead.ac.in",
    orcid_id: "0009-0005-0119-9263",
    google_scholar: "https://scholar.google.com/citations?user=-O1B76YAAAAJ&hl=en",
    linkedin: "https://www.linkedin.com/in/k-g-viswanadhan-0298a167/",
    researchgate_scopus: "https://www.researchgate.net/profile/K-Viswanadhan",
    professional_biography: "Prof. K G Viswanadhan serves as Dean (Accreditation) at LEAD College (Autonomous), Palakkad. He holds BTech, ME, MBA, MCA, PGDCA and PhD degrees. He also holds a Certification in Leadership & Management from Chartered Management Institute, United Kingdom and has 37 years of teaching, research, and industry experience. His areas of expertise include Administration, Teaching, Quality assurance, Assessment, and Accreditation.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management", institution: "Indian Institute of Science (IISc), Bangalore", year: "2006" },
      { degree: "MBA", discipline: "Information Systems", institution: "Bharathiar University", year: "2009" },
      { degree: "MCA", discipline: "Computer Applications", institution: "Bharathiar University", year: "2013" },
      { degree: "PGDCA", discipline: "Computer Applications", institution: "Bharathiar University", year: "2001" },
      { degree: "Master's Degree", discipline: "Production Engineering", institution: "PSG College of Technology, Coimbatore", year: "1989" },
      { degree: "Bachelor's Degree", discipline: "Mechanical Engineering", institution: "Kerala University", year: "1986" },
    ],
    teaching_experience: 37, industry_experience: 0, research_experience: 24,
    areas_of_expertise: ["Administration", "Teaching", "Quality assurance", "Assessment", "Accreditation"],
    research_interests: ["General Management", "Quality", "Higher Education", "Operations Management"],
    image: "/faculty/photos/f1.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. Krishnapriya M A",
    designation: "Associate Professor",
    department_program: "MCA",
    department: "MCA",
    institutional_roles: "Faculty",
    email: "dr.krishnapriya@lead.ac.in",
    orcid_id: "0009-0007-2967-6847",
    google_scholar: "https://scholar.google.com/citations?hl=en",
    linkedin: "https://www.linkedin.com/in/dr-krishna-priya-m-a-5b17a6228/",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=57850671300",
    professional_biography: "Dr. Krishnapriya M. A. serves as an Associate Professor at LEAD College (Autonomous), Palakkad. She holds a Ph.D. in Computer Science and brings over two decades of teaching experience.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Computer Science - Knowledge Management", institution: "Bharathiar University", year: "2023" },
      { degree: "Master's Degree", discipline: "MCA", institution: "Bharathiar University", year: "2001" },
      { degree: "Bachelor's Degree", discipline: "BSc", institution: "Vellalar College for Women, Bharathiar University", year: "1997" },
    ],
    teaching_experience: 20, industry_experience: 3, research_experience: 5,
    areas_of_expertise: ["Software Engineering", "Data Science", "Knowledge Management", "Big Data", "Machine Learning"],
    research_interests: ["Machine Learning", "Quantum Computing"],
    image: "/faculty/photos/f41.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. Naibi Kurian",
    designation: "Assistant Professor (Senior Grade)",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Faculty, Mentor, Training LOT",
    email: "Dr.naibikurian@lead.ac.in",
    orcid_id: "0009-0001-9462-3641",
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Dr. Naibi Kurian serves as Assistant Professor (Senior Grade) in the MBA Program at LEAD College (Autonomous), Palakkad. He holds a Ph.D. in Marketing from Bharathiar University and has six years of teaching experience in management education along with ten years of prior industry experience.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Marketing", institution: "Bharathiar University", year: "2025" },
      { degree: "MBA", discipline: "Marketing", institution: "Bharathiar University", year: "1998" },
      { degree: "BTech", discipline: "Mechanical Engineering", institution: "Mangalore University", year: "1996" },
    ],
    teaching_experience: 6, industry_experience: 10, research_experience: 0,
    areas_of_expertise: ["Marketing Analytics", "Consumer Behaviour", "Retail Management"],
    research_interests: ["Predictive Modelling in Marketing", "Customer Segmentation and Behavioural Analytics", "Retail Patronage Behaviour", "Machine Learning Applications in Marketing", "Data-Driven Consumer Insights"],
    image: "/faculty/photos/f7.jpeg",
    banner_image: null,
  },
  // ── L ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Lakshmi R Nair",
    designation: "Publications Officer-in-charge",
    department_program: "Management",
    department: "MBA",
    institutional_roles: "Publications Officer-in-charge",
    email: null,
    orcid_id: null,
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Dr. Lakshmi R Nair is an expert in language and literature with a strong focus on writing styles, rhetoric, and communicative strategies.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "English Literature", institution: "Bharathiar University, Coimbatore", year: "2019" },
      { degree: "M.Phil.", discipline: "English Literature", institution: "Bharathiar University, Coimbatore", year: "2014" },
      { degree: "Master's Degree", discipline: "English Literature", institution: "Mahatma Gandhi University, Kerala", year: "2009" },
      { degree: "Bachelor's Degree", discipline: "English Literature", institution: "Mahatma Gandhi University, Kerala", year: "2007" },
    ],
    teaching_experience: 5, industry_experience: 0, research_experience: 12,
    areas_of_expertise: ["Resistance Studies in Literature", "Contemporary Studies in Literature", "Cultural Studies in Literature", "Research Methodology"],
    research_interests: ["Communication in Management Studies", "English Language and Literature"],
    image: "/faculty/photos/f32.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. Linda Silvya J",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Batch Coordinator (2024-2026 batch)",
    email: "dr.linda@lead.ac.in",
    orcid_id: "0009-0005-7907-8947",
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Dr. J. Linda Silvya is an Assistant Professor specializing in Commerce and Finance with over nine years of teaching experience in higher education.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Finance", institution: "Bharathi University", year: "2018–2025" },
      { degree: "M.Phil.", discipline: "Finance", institution: "Bharathi University", year: "2023" },
      { degree: "Master's Degree", discipline: "M.Com (Computer Application)", institution: "University of Calicut", year: "2011–2013" },
      { degree: "Bachelor's Degree", discipline: "B.Com (Computer Application)", institution: "University of Calicut", year: "2008–2011" },
    ],
    teaching_experience: 10, industry_experience: 0, research_experience: 2,
    areas_of_expertise: ["Financial Investment", "Foreign Direct Investment", "Microfinance"],
    research_interests: ["Financial Investment", "Foreign Direct Investment", "Microfinance"],
    image: "/faculty/photos/f21.jpeg",
    banner_image: null,
  },
  // ── M ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Shaju Meetna",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Head, Centre for Research, Consultancy, and Publications; Editor, LEADER: International Journal of Business Management",
    email: "Shaju.m@lead.ac.in",
    orcid_id: "0009-0007-9376-2029",
    google_scholar: "https://scholar.google.com/citations?user=RqnbTHQAAAAJ&hl=en",
    linkedin: "https://in.linkedin.com/in/shaju-meetna-1685ba130",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=59223162800",
    professional_biography: null,
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Organizational Behaviour", institution: "Amrita Vishwa Vidyapeetham", year: "" },
      { degree: "Master's Degree", discipline: "MBA (Human Resources)", institution: "Bharathiar University", year: "2017" },
      { degree: "Bachelor's Degree", discipline: "BSc", institution: "Annamalai University", year: "2010" },
      { degree: "Associate Degree", discipline: "", institution: "IGNOU + Indian Air Force", year: "2006" },
    ],
    teaching_experience: 3, industry_experience: 18, research_experience: 5,
    areas_of_expertise: ["Organizational Behaviour", "Human Resources Management", "Business Ethics", "Performance Management Systems"],
    research_interests: ["Organizational Mis Behaviour", "Ethics and Morality", "Indian Knowledge Systems", "Qualitative Research"],
    image: "/faculty/photos/f29.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Megha P M",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Head, LEAD BI",
    email: "Dr.megha@lead.ac.in",
    orcid_id: "0009-0004-3505-1446",
    google_scholar: null,
    linkedin: "http://www.linkedin.com/in/meghap-m",
    researchgate_scopus: null,
    professional_biography: "Dr. Megha P M is an academician, researcher, and startup mentor with a strong background in biotechnology and translational research. She holds a Ph.D. in Microbiology from Bharathiar University and currently serves as Head of Entrepreneurship and LEAD Business Incubator at LEAD College, Palakkad.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Microbiology", institution: "Bharathiar University", year: "2009–2018" },
      { degree: "M.Phil.", discipline: "Microbiology", institution: "Bharathiar University", year: "2007–2008" },
      { degree: "Master's Degree", discipline: "Microbiology", institution: "Madras University", year: "2005–2007" },
      { degree: "Bachelor's Degree", discipline: "Microbiology", institution: "Calicut University", year: "2002–2005" },
    ],
    teaching_experience: 15, industry_experience: 15, research_experience: 10,
    areas_of_expertise: ["Entrepreneurship Development and Startup Mentoring", "Research Project Design and Grant Facilitation"],
    research_interests: [],
    image: "/faculty/photos/f18.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Urmila R Menon",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Faculty, Mentor",
    email: "urmila@lead.ac.in",
    orcid_id: "0000-0002-8447-4945",
    google_scholar: "https://scholar.google.com/citations?user=eJlEXjsAAAAJ&hl=en",
    linkedin: "https://www.linkedin.com/in/dr-urmila-r-menon-536a6a381",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=57194334972",
    professional_biography: "Dr. Urmila R. Menon is an Assistant Professor of Commerce at LEAD College. She holds a Ph.D. in Commerce from the University of Calicut and is UGC-NET qualified. With over three and a half years of teaching experience, she specializes in financial management, accounting, security analysis, portfolio management, and management control systems.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Commerce", institution: "University of Calicut", year: "2023" },
      { degree: "M.Phil.", discipline: "Commerce - Advanced Financial Management", institution: "University of Calicut", year: "2018" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "University of Calicut", year: "2016" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "University of Calicut", year: "2014" },
    ],
    teaching_experience: 3.5, industry_experience: 0, research_experience: 3,
    areas_of_expertise: ["Finance"],
    research_interests: ["Finance", "HR", "Educational Research"],
    image: "/faculty/photos/f14.jpg",
    banner_image: null,
  },
  // ── N ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Sabina A Nair",
    designation: "Assistant Professor (Senior Grade)",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Served as Internship Coordinator",
    email: "dr.sabina@lead.ac.in",
    orcid_id: "0009-0002-3978-5856",
    google_scholar: "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=sabina+A+Nair",
    linkedin: "https://www.linkedin.com/in/dr-sabina-nair-053379ba/",
    researchgate_scopus: "http://www.researchgate.net/scientific-contributions/Sabina-A-Nair-2331440390",
    professional_biography: "Dr. Sabina A Nair is an Assistant Professor (Senior Grade) in the Department of Management at LEAD College, Palakkad, with a Ph.D. in Neuromarketing from the University of Madras. She has teaching experience from institutions such as IILM University, Gurugram and the University of Madras, with multiple publications in Scopus indexed and UGC listed journals and presentations at national and international conferences, including at the National University of Singapore.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Commerce / Neuromarketing", institution: "University of Madras", year: "2021" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "Calicut University", year: "2007" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "Calicut University", year: "2005" },
    ],
    teaching_experience: 11, industry_experience: 3, research_experience: 4,
    areas_of_expertise: ["Neuromarketing", "Consumer Psychology"],
    research_interests: ["Circular Economy", "Indigenous Studies", "Micro Finance"],
    image: "/faculty/photos/f11.jpg",
    banner_image: null,
  },
  // ── P ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Pramod V",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Associate Dean (Student Affairs)",
    email: "pramod@lead.ac.in",
    orcid_id: "0009-0007-8589-5649",
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/pramod-v-083b0bb1",
    researchgate_scopus: null,
    professional_biography: "Mr. Pramod V holds an M.Com from SN College, Alathur and an MBA from DMS Palayad. He has been serving as an Assistant Professor at LEAD College since 2014 and brings around 13 years of academic experience along with about one year of industry experience. His research interests include crowdfunding and fintech. He has also authored a book titled \"Role of Content Marketing in Customer Engagement\". He is passionate about student engagement and applies mind-mapping techniques in academics to enhance student learning outcomes.",
    educational_qualifications: [
      { degree: "MBA", discipline: "HR & Finance", institution: "Kannur University", year: "2009–11" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "University of Calicut", year: "2007–09" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "University of Calicut", year: "2005–07" },
    ],
    teaching_experience: 13, industry_experience: 1, research_experience: 6,
    areas_of_expertise: ["Behavioral Finance", "Financial Management"],
    research_interests: ["Crowd funding", "Sustainable Development", "ESG integration"],
    image: "/faculty/photos/f5.jpg",
    banner_image: null,
  },
  // ── R ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Mr. Ranjith Karat",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Functional Head - Data Analytics and Operation",
    email: "ranjithkarat@lead.ac.in",
    orcid_id: "0009-0001-3626-8370",
    google_scholar: "https://scholar.google.com/citations?user=r_MLNnIAAAAJ&hl=en&oi=ao",
    linkedin: "https://www.linkedin.com/in/ranjith-karat-163103227/",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=59549074700",
    professional_biography: "Mr. Ranjith Karat is an Assistant Professor of Management at LEAD College (Autonomous), Palakkad. His research focuses on contrarian investment strategies in the Indian stock market.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Finance", institution: "Kerala University of Fisheries and Ocean Studies", year: "2020–2026" },
      { degree: "MBA", discipline: "Data Analytics", institution: "Mizoram University", year: "2024–2026" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "University of Calicut", year: "2010–2012" },
      { degree: "Bachelor's Degree", discipline: "BBA", institution: "University of Calicut", year: "2007–2010" },
    ],
    teaching_experience: 8, industry_experience: 1, research_experience: 5,
    areas_of_expertise: ["Decision Science", "Descriptive Analytics", "Prescriptive Analytics", "Contrarian Investment"],
    research_interests: ["Contrarian Investment", "Indian Stock Market"],
    image: "/faculty/photos/f26.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Rajani Ramachandran",
    designation: "Assistant Professor",
    department_program: "English",
    department: "MBA",
    institutional_roles: "Teaching",
    email: "dr.rajaniram@lead.ac.in",
    orcid_id: "0000-0002-3546-1793",
    google_scholar: null,
    linkedin: "http://www.linkedin.com/in/dr-rajani-ramachandran",
    researchgate_scopus: null,
    professional_biography: "Dr. Rajani Ramachandran serves as Assistant Professor of English at LEAD College (Autonomous), Palakkad. She holds a Ph.D. in English Literature with a specialization in Women Studies from Bharathiar University.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Women Studies (English Literature)", institution: "Bharathiar University", year: "2025" },
      { degree: "M.Phil.", discipline: "English Language and Literature", institution: "Bharathiar University", year: "2019" },
      { degree: "Master's Degree", discipline: "English Language and Literature", institution: "Annamalai University", year: "2010" },
      { degree: "Bachelor's Degree", discipline: "English Language and Literature", institution: "University of Calicut", year: "1997" },
    ],
    teaching_experience: 22, industry_experience: 0, research_experience: 8,
    areas_of_expertise: ["Women Studies", "English Language Teaching", "Cultural Studies", "Gender Studies"],
    research_interests: ["Women's Rights", "Feminism", "Empowerment"],
    image: "/faculty/photos/f31.jpg",
    banner_image: null,
  },
  // ── S ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Yasmin Samad",
    designation: "Assistant Professor and Administrator",
    department_program: "Management (MBA & MCA)",
    department: "MBA",
    institutional_roles: "Academic Administrator",
    email: "yasmin@lead.ac.in",
    orcid_id: "0009-0004-5111-2835",
    google_scholar: "https://scholar.google.com/citations?user=QKIksrwAAAAJ",
    linkedin: "https://www.linkedin.com/in/yasmin-samad",
    researchgate_scopus: null,
    professional_biography: "Yasmin Samad is an experienced academic administrator and human resource professional with over three decades of experience spanning industry and higher education.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Human Resource Management", institution: "Bharathiar University", year: "2026" },
      { degree: "M.Phil.", discipline: "Human Resource Management", institution: "Bharathiar University", year: "2022" },
      { degree: "MBA", discipline: "Human Resource Management", institution: "IGNOU", year: "2018" },
      { degree: "Master's Degree", discipline: "MHRM", institution: "Alagappa University", year: "2006" },
      { degree: "Post Graduate Diploma", discipline: "PGDPM", institution: "National Institute of Personnel Management Calcutta", year: "1992" },
      { degree: "Bachelor's Degree", discipline: "BSc", institution: "University of Calicut", year: "1989" },
    ],
    teaching_experience: 15, industry_experience: 15, research_experience: 4,
    areas_of_expertise: ["Institutional Administration", "Compliance and Governance", "Policy Development", "Employee Engagement", "Academic Administration", "Liaison with Statutory Bodies", "Employee Relations"],
    research_interests: ["Human Resource Management", "Accreditations", "International Collaborations"],
    image: "/faculty/photos/f23.jpg",
    banner_image: null,
  },
  {
    full_name: "Sangeetha Santhosh",
    designation: "Academic Associate",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Academic Associate",
    email: "sangeetha.s@lead.ac.in",
    orcid_id: null,
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Ms. Sangeetha Santhosh serves as an Academic Associate in Marketing Management at LEAD College (Autonomous), Palakkad.",
    educational_qualifications: [
      { degree: "MBA", discipline: "Finance and Marketing", institution: "University of Calicut", year: "2022–2024" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "Mahatma Gandhi University", year: "2018–2021" },
    ],
    teaching_experience: 0, industry_experience: 0, research_experience: 0,
    areas_of_expertise: ["Brand Management", "Digital Marketing", "Sustainability and ESG in Marketing", "Consumer Behavior"],
    research_interests: [],
    image: "/faculty/photos/f38.jpeg",
    banner_image: null,
  },
  {
    full_name: "Santhosh V Krishnan",
    designation: "Professor of Practice",
    department_program: "Department of Computer Applications",
    department: "MCA",
    institutional_roles: "HoD MCA",
    email: "santhosh.v.krishnan@lead.ac.in",
    orcid_id: null,
    google_scholar: null,
    linkedin: "http://www.linkedin.com/in/santhoshvkrishnan",
    researchgate_scopus: null,
    professional_biography: "Mr. Santhosh V Krishnan serves as Professor of Practice at LEAD College (Autonomous), Palakkad. He holds an MCA and has over 25 years of industry experience in software delivery and development.",
    educational_qualifications: [
      { degree: "M.Phil.", discipline: "Computer Science", institution: "Bharathiar University, Coimbatore", year: "2008" },
      { degree: "Master's Degree", discipline: "MCA", institution: "Cochin University of Science & Technology", year: "2000" },
      { degree: "Bachelor's Degree", discipline: "B.Sc (Chemistry)", institution: "University of Calicut", year: "1996" },
    ],
    teaching_experience: 0, industry_experience: 25, research_experience: 0,
    areas_of_expertise: ["Cloud-based Architecture for Scalable Solutions", "Healthcare Software Development using AWS and Microsoft Azure", "AWS Machine Learning", "Full Stack Development and Delivery", "Software Systems for Healthcare Automation"],
    research_interests: ["Cloud AI Models for Prediction and Prevention", "Interdisciplinary Collaboration in Tech-Driven Healthcare"],
    image: "/faculty/photos/f42.jpg", // f42 — no file available
    banner_image: null,
  },
  {
    full_name: "Dr. Sarithambika K P",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Batch Coordinator (2024-2026 batch)",
    email: "sarithambika@lead.ac.in",
    orcid_id: "0000-0003-3072-861X",
    google_scholar: "https://scholar.google.com/citations?user=h3IQ3zUAAAAJ&hl=en",
    linkedin: "https://www.linkedin.com/in/sarithambika-kp-906b1a390/",
    researchgate_scopus: null,
    professional_biography: "Dr. Sarithambika K. P is an Assistant Professor in the MBA program specializing in finance and entrepreneurship at LEAD College (Autonomous) since May 2024. She earned her Ph.D. from the University of Calicut with research on socio-economic dimensions and entrepreneurial development of differently-abled entrepreneurs in Kerala.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Entrepreneurship", institution: "University of Calicut", year: "2024" },
      { degree: "Master's Degree", discipline: "M.Com (Financial Management)", institution: "University of Calicut", year: "2018" },
      { degree: "Bachelor's Degree", discipline: "B.Com (Co-operation)", institution: "University of Calicut", year: "2015" },
    ],
    teaching_experience: 2, industry_experience: 0, research_experience: 5,
    areas_of_expertise: ["Finance", "Entrepreneurship"],
    research_interests: ["Entrepreneurship"],
    image: "/faculty/photos/f17.jpg",
    banner_image: null,
  },
  {
    full_name: "Satyendra Kushwaha",
    designation: "Academic Research Associate",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Research Department Cell, Conference and Publications",
    email: "Satyendra.k@lead.ac.in",
    orcid_id: "0009-0008-8948-5820",
    google_scholar: "https://scholar.google.com/citations?user=xA9xfEYAAAAJ&hl=en",
    linkedin: "http://www.linkedin.com/in/satyendra-kushwaha-905633200",
    researchgate_scopus: "https://www.researchgate.net/profile/Satyendra-Kushwaha-4",
    professional_biography: "Satyendra Kushwaha is a finance researcher with a strong interest in financial economics, financial markets, and global economic dynamics.",
    educational_qualifications: [
      { degree: "Master's Degree", discipline: "MBA (Finance)", institution: "University of Calicut", year: "2025" },
      { degree: "Bachelor's Degree", discipline: "BBA", institution: "Pokhara University", year: "2023" },
    ],
    teaching_experience: 0, industry_experience: 2, research_experience: 2.5,
    areas_of_expertise: ["Finance", "Economics", "Human Resource Management"],
    research_interests: ["Finance", "Economics", "Human Resource Management"],
    image: "/faculty/photos/f37.jpg",
    banner_image: null,
  },
  {
    full_name: "Shafeena Ahmed",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Teaching",
    email: "shafeena@lead.ac.in",
    orcid_id: null,
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Shafeena Ahmed is an Executive Assistant and strategic communication professional with over nine years of experience supporting senior leadership in education and corporate environments.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management", institution: "Noorul Islam Centre for Higher Education", year: "Pursuing" },
      { degree: "MBA", discipline: "HR and Marketing", institution: "MG University", year: "2022" },
      { degree: "Bachelor's Degree", discipline: "Information Technology", institution: "Calicut University", year: "2012" },
    ],
    teaching_experience: 3, industry_experience: 6, research_experience: 0,
    areas_of_expertise: [], research_interests: [],
    image: "/faculty/photos/f28.jpg",
    banner_image: null,
  },
  {
    full_name: "Mr. Shankar Raman R",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Faculty In-Charge LEADOGRAPHY & IEEE SB Counselor",
    email: "shankar.rr@lead.ac.in",
    orcid_id: "0009-0009-4167-1699",
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: null,
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Human Resources Management", institution: "Bharathiar University / Sri Krishna Arts & Science College", year: "2022–Present" },
      { degree: "MBA", discipline: "Operations & Marketing", institution: "Anna University / RVS Institute of Management Studies", year: "2018–2020" },
      { degree: "Bachelor's Degree", discipline: "Mechanical Engineering", institution: "Anna University / VSB College of Engineering Technical Campus", year: "2014–2017" },
    ],
    teaching_experience: 4, industry_experience: 2, research_experience: 0,
    areas_of_expertise: ["Data Visualization and Business Intelligence", "Supply Chain and Logistics", "HR Analytics and Employee Retention"],
    research_interests: ["Cognitive Load in Dashboards", "Last Mile Logistics Optimization", "Predictive Attrition and Retention Analytics"],
    image: "/faculty/photos/f30.jpg", // f30 — no file available
    banner_image: null,
  },
  {
    full_name: "Dr. Sheena M S",
    designation: "Controller of Examinations & Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Controller of Examinations",
    email: "Dr.sheena@lead.ac.in",
    orcid_id: "0000-0002-0068-0013",
    google_scholar: null,
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Dr. Sheena M. S serves as Controller of Examinations and Assistant Professor at LEAD College (Autonomous), Palakkad. She holds an M.Com and a Ph.D. in Commerce from the University of Kerala and has also completed a Post-Doctoral Fellowship. She is qualified with NET and JRF. Her doctoral research focused on the functional operations of micro enterprises run by women entrepreneurs in Kerala.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Commerce", institution: "University of Kerala", year: "2020" },
      { degree: "MBA", discipline: "Finance", institution: "Bharathidasan University", year: "2026" },
      { degree: "Master's Degree", discipline: "M.Com", institution: "University of Kerala", year: "2010–2012" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "University of Kerala", year: "2007–2010" },
    ],
    teaching_experience: 5.5, industry_experience: 0, research_experience: 6,
    areas_of_expertise: ["Behavioral Finance", "Financial Management", "Entrepreneurship"],
    research_interests: ["Micro Finance", "Entrepreneurship"],
    image: "/faculty/photos/f12.jpg",
    banner_image: null,
  },
  {
    full_name: "Sijin T C",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Faculty, OBT Incharge",
    email: "sijin@lead.ac.in",
    orcid_id: "0009-0009-9343-4900",
    google_scholar: null,
    linkedin: "https://www.linkedin.com/in/sijin-tc",
    researchgate_scopus: null,
    professional_biography: "Mr. Sijin T.C. serves as an Assistant Professor at LEAD College, where he has been contributing since 2017. With nearly a decade of experience in higher education, he is actively involved in teaching, mentoring, and student development initiatives.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management", institution: "Noorul Islam University", year: "2025" },
      { degree: "MBA", discipline: "Finance and Marketing", institution: "University of Calicut", year: "2014" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "University of Calicut", year: "2011" },
    ],
    teaching_experience: 8, industry_experience: 1, research_experience: 0,
    areas_of_expertise: ["Entrepreneurship", "Training and Development", "Outbound Training"],
    research_interests: ["Training and Development", "Outbound Training"],
    image: "/faculty/photos/f24.jpg",
    banner_image: null,
  },
  {
    full_name: "Dr. Sindhu R",
    designation: "Professor",
    department_program: "Quality Assurance",
    department: "MBA",
    institutional_roles: "Dean (Quality Assurance)",
    email: "sindhu.r@lead.ac.in",
    orcid_id: "0009-0005-7886-6861",
    google_scholar: "https://scholar.google.co.in/citations?user=HNzmjZoAAAAJ&hl=en&authuser=2",
    linkedin: null,
    researchgate_scopus: null,
    professional_biography: "Dr. Sindhu R serves as Dean (Quality Assurance) at LEAD College (Autonomous), Palakkad. She holds a degree in Electronics and Communication Engineering and a Ph.D from IISc, Bangalore. She has 35 years of teaching experience at NSS College of Engineering, Palakkad. Her areas of expertise include assessment of student performance and accreditation of programmes.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Computer Assisted Evaluation of Student Performance in an Engineering Course", institution: "Indian Institute of Science, Bangalore", year: "2007" },
      { degree: "M.Tech", discipline: "Applied Electronics", institution: "PSG College of Technology, Coimbatore", year: "1998" },
      { degree: "Bachelor's Degree", discipline: "Electronics and Communication Engineering", institution: "University of Mysore", year: "1989" },
    ],
    teaching_experience: 35, industry_experience: 0, research_experience: 0,
    areas_of_expertise: ["Teaching", "Accreditation"],
    research_interests: ["Communication", "Image Processing"],
    image: "/faculty/photos/f2.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. R. Sona",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Teaching",
    email: "sona.r@lead.ac.in",
    orcid_id: "0000-0003-0288-392X",
    google_scholar: "https://scholar.google.com/citations?user=R1hiuOcAAAAJ&hl=en",
    linkedin: "http://www.linkedin.com/in/dr-sona-ramachandran",
    researchgate_scopus: null,
    professional_biography: "Dr. R. Sona is an academician and management professional with over 15 years of experience in higher education and industry. She holds a Ph.D. in Human Resource Management from Bharathiar University.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Human Resource Management", institution: "Bharathiar University", year: "2025" },
      { degree: "UGC-NET", discipline: "Management", institution: "University Grants Commission", year: "2020" },
      { degree: "MBA", discipline: "Human Resource & Marketing", institution: "Sankara Institute of Management Science", year: "2008" },
      { degree: "Bachelor's Degree", discipline: "Designing Interiors & Exteriors", institution: "Avinashilingam Deemed University", year: "2006" },
    ],
    teaching_experience: 15, industry_experience: 3, research_experience: 0,
    areas_of_expertise: ["Human Resource Management and Organizational Behavior", "HR Analytics and People Analytics", "Industry 4.0 and Artificial Intelligence in HRM", "Knowledge Management and Organizational Commitment", "Employee Well-being, Stress Management and Work Engagement"],
    research_interests: ["Knowledge Hiding Behavior", "Perceived Organizational Support", "Affective and Organizational Commitment", "Artificial Intelligence Strategy in HR", "Innovative Work Behavior", "Techno-Stress and Occupational Stress", "Agile Workforce and Skill Gap (Industry 4.0)", "Green HRM Practices", "Emotional Intelligence and Intrapreneurship", "Employee Experience and Workforce Transformation"],
    image: "/faculty/photos/f22.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. Subhashini Durai",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Teaching",
    email: "subhashini@lead.ac.in",
    orcid_id: "0000-0002-8061-2781",
    google_scholar: "https://scholar.google.com/citations?user=9dNkiKAAAAAJ",
    linkedin: "https://www.linkedin.com/in/dr-subhashini-d-33a3bb120/",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=57739643600",
    professional_biography: "Dr. Subhashini Durai is an Assistant Professor in the MBA Department at LEAD College (Autonomous), Palakkad. She holds a Ph.D. in Management Science from Anna University and an M.Phil. from Bharathiar University, along with dual MBA degrees in Human Resource Management and Production and Operations Management.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management Science", institution: "Anna University", year: "2020" },
      { degree: "M.Phil.", discipline: "Management Science", institution: "Bharathiar University", year: "2013" },
      { degree: "Master's Degree", discipline: "MBA (HRM and POM)", institution: "Alagappa University", year: "2010 and 2021" },
      { degree: "Bachelor's Degree", discipline: "BCS", institution: "University of Madras", year: "2002" },
    ],
    teaching_experience: 6, industry_experience: 12, research_experience: 10,
    areas_of_expertise: ["Data Analytics", "Business Analytics", "Artificial Intelligence", "Predictive Analytics", "Lean Manufacturing", "OB-HR"],
    research_interests: ["Business Analytics", "Artificial Intelligence", "Predictive Analytics", "Lean Manufacturing", "OB-HR"],
    image: "/faculty/photos/f20.jpeg",
    banner_image: null,
  },
  {
    full_name: "Dr. Syamraj KP",
    designation: "Assistant Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Trading Club - Coordinator",
    email: "syamraj.kp@lead.ac.in",
    orcid_id: "0009-0008-0198-2145",
    google_scholar: null,
    linkedin: "http://www.linkedin.com/in/dr-syamraj-kp-92945458",
    researchgate_scopus: "https://www.scopus.com/authid/detail.uri?authorId=58505280200",
    professional_biography: "Dr. Syamraj KP is an academic and researcher specializing in finance, risk analytics, and corporate governance. He holds a Ph.D. in Commerce (Financial Market) from the University of Kerala and serves as Assistant Professor of Finance and Accounting at LEAD College. His teaching focuses on financial analytics, investment management, and financial forecasting using Python.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Commerce", institution: "University of Kerala", year: "2025" },
      { degree: "M.Phil.", discipline: "Commerce", institution: "University of Kerala", year: "2017" },
      { degree: "Master's Degree", discipline: "M.Com (Accounting & Taxation)", institution: "Pondicherry University", year: "2013" },
      { degree: "Bachelor's Degree", discipline: "B.Com", institution: "University of Calicut", year: "2011" },
    ],
    teaching_experience: 6, industry_experience: 1, research_experience: 6,
    areas_of_expertise: ["Financial Markets and Institutions", "Applied Econometrics for Finance", "Financial Modeling and Forecasting", "Algorithmic Trading and Quantitative Strategy Design"],
    research_interests: ["Financial Market Risk Measurement", "Volatility Modelling", "Tail Risk", "Sustainable Finance", "ESG Integration", "Climate Risk Analysis"],
    image: "/faculty/photos/f16.jpg",
    banner_image: null,
  },
  // ── V ────────────────────────────────────────────────────────────────────────
  {
    full_name: "Dr. Wranton Perez R",
    designation: "Professor",
    department_program: "MBA",
    department: "MBA",
    institutional_roles: "Teaching Faculty",
    email: "wranton@lead.ac.in",
    orcid_id: null,
    google_scholar: "https://scholar.google.com/citations?user=xDZdxvwAAAAJ",
    linkedin: "http://www.linkedin.com/in/dr-r-wranton-perez-93898824",
    researchgate_scopus: null,
    professional_biography: "Dr. R. Wranton Perez is a Professor in the MBA department and a seasoned academic professional with over 30 years of experience in higher education. He holds a Ph.D. in Management from Pondicherry University with research focused on Information Security Management System implementation among data centers in Tamil Nadu. He has held senior academic and administrative roles across institutions in India, Tanzania, and Zambia, including Dean of the School of Information Technology at St. Joseph University in Tanzania and Acting Principal of its College of Engineering and Technology. He is a certified Lean Six Sigma AI Yellow Belt and has contributed to accreditation systems aligned with ISO, NAAC, and NBA standards.",
    educational_qualifications: [
      { degree: "Ph.D.", discipline: "Management, Information Security Management", institution: "School of Management, Pondicherry University", year: "2010" },
      { degree: "MBA", discipline: "Systems & Operations", institution: "National Institute of Technology (Regional Engineering College), Tiruchirappalli", year: "1994" },
      { degree: "Bachelor's Degree", discipline: "Computer Science and Engineering", institution: "Madurai Kamaraj University", year: "1991" },
    ],
    teaching_experience: 30, industry_experience: 1, research_experience: 7,
    areas_of_expertise: ["Business Analytics (MS Excel, Power BI, Tableau)", "Operations and Supply Chain Management", "Systems Design"],
    research_interests: ["Lean Management", "Operational Efficiency", "AI-Augmented Managerial Decision"],
    image: "/faculty/photos/f3.jpg",
    banner_image: null,
  },
];

export const facultyData: FacultyMember[] = raw.map((m) => ({
  ...m,
  slug: slugify(m.full_name),
}));